select `ID`, `DEPTID`,  `CREATEDAT`, `BILLTYPE`, `BILLTYPEATOMIC`,  
`TOTAL`,
`GRANTTOTAL`,
`GRNNETTOTAL`,
`NETTOTAL`,
`PAIDAMOUNT`,
`BALANCE`, 
`DEPARTMENT_ID`,
 `INSTITUTION_ID`,
 `PAYMENTMETHOD`,
 `REFERENCEBILL_ID`,
`FORWARDREFERENCEBILL_ID`,
`BACKWARDREFERENCEBILL_ID`
from bill 
order by `ID` desc limit 10;
