SELECT `ID`, 
`DTYPE`, 
`BILLTYPE`,
 `BILLTYPEATOMIC`, `TOTAL`, `NETTOTAL`, `BACKWARDREFERENCEBILL_ID` , `DISCOUNT`, `CREATEDAT`, `BALANCE`,`BILLDATE`, `BILLTIME`, `PAYMENTMETHOD`, `INSID`, `DEPTID` FROM bill order by id desc LIMIT 10;
