select `ID`, 
`REFERENCENUMBER`,
`PAIDAMOUNT`, 
`SETTLEDAMOUNTBYPATIENT`, `SETTLEDAMOUNTBYSPONSOR`, `PAIDAT`,
`DEPTID`, 
`COMMENTS`,
 `CREATEDAT`,
 `BILLTYPE`, 
`BILLTYPEATOMIC`, 
 `DTYPE`
`TOTAL`,
`GRANTTOTAL`,
`GRNNETTOTAL`,
`NETTOTAL`,
`PAIDAMOUNT`,
`BALANCE`, 
`DEPARTMENT_ID`,
 `INSTITUTION_ID`,
 `PAYMENTMETHOD`,
 `REFERENCEBILL_ID`,
`FORWARDREFERENCEBILL_ID`,
`BACKWARDREFERENCEBILL_ID`,
`CREDITCOMPANY_ID`
from bill 
order by `ID` desc limit 10;
select `ID`, `CREATEDAT`, `BILL_ID` , `PATIENTENCOUNTER_ID`
from billitem order by id desc;
select `ID`, `BILLITEM_ID` , `CREATEDAT`, `INVESTIGATION_ID` from patientinvestigation order by id desc limit 10;
