SELECT id, `NETRATE`, `RATE`, `QTY`, `NETVALUE`, `GROSSVALUE` FROM billitem order by id desc LIMIT 1;
select `ID`, `LINENETRATE`, `LINEGROSSTOTAL`, `GROSSRATE`, `GROSSTOTAL`, `LINEGROSSRATE`, `LINECOST`, `QUANTITY`, `QUANTITYBYUNITS`,
 `LINECOSTRATE`, `VALUEATCOSTRATE`, `VALUEATPURCHASERATE`, `VALUEATRETAILRATE` from billitemfinancedetails order by id desc limit 2;
select `ID`, `QTY`, `RETAILRATE`, `PURCHASERATE`, `PURCHASERATEPACK`, `RETAILRATEPACK`, `PURCHASEVALUE`, `RETAILVALUE`, `STOCK_ID`, `ITEMBATCH_ID` from pharmaceuticalbillitem order by id desc limit 1;
select `ID` , `CREATEDAT`, `BILLTYPEATOMIC`,  `NETTOTAL`, `TOTAL`, `SALEVALUE` from Bill order by id desc limit 1;
select `ID`, `NETTOTAL`, `GROSSTOTAL`, `TOTALCOSTVALUE`, `TOTALCOSTVALUE`, `TOTALPURCHASEVALUE`, `TOTALRETAILSALEVALUE` from billfinancedetails order by id desc limit 1;