-- Check bill items created on 9th July 2025
SELECT id, `CREATEDAT`, `BILLITEMFINANCEDETAILS_ID`, `NETRATE`, `RATE`, `QTY`, `NETVALUE`, `GROSSVALUE` 
FROM billitem 
WHERE `BILL_ID` = 3312022
ORDER BY id DESC;

-- -- Check bill item finance details created on 9th July 2025
SELECT `ID`, `CREATEDAT`, `LINENETRATE`, `LINEGROSSTOTAL`, `GROSSRATE`, `GROSSTOTAL`, 
       `LINEGROSSRATE`, `LINECOST`, `QUANTITY`, `QUANTITYBYUNITS`,
       `LINECOSTRATE`, `VALUEATCOSTRATE`, `VALUEATPURCHASERATE`, `VALUEATRETAILRATE` 
FROM billitemfinancedetails 
WHERE `ID` < 3314958
  AND `ID` > 3312249
ORDER BY id DESC;
-- 
-- -- Check pharmaceutical bill items created on 9th July 2025
SELECT `ID`, `QTY`, `RETAILRATE`, `PURCHASERATE`, `COSTRATE`,  `CREATEDAT`
       `PURCHASERATEPACK`, `RETAILRATEPACK`, `COSTRATEPACK`, 
       `PURCHASEVALUE`, `RETAILVALUE`, `COSTVALUE`,  
       `STOCK_ID`, `ITEMBATCH_ID` 
FROM pharmaceuticalbillitem
WHERE `ID` < 3314958
  AND `ID` > 3312249
ORDER BY id DESC;
-- 
-- -- Check bills created on 9th July 2025
SELECT `ID`, `CREATEDAT`, `BILLTYPEATOMIC`, `NETTOTAL`, `TOTAL`, `SALEVALUE` 
FROM bill 
WHERE `ID` < 3314958
  AND `ID` > 3312249
ORDER BY id DESC;
-- 
-- -- Check bill finance details created on 9th July 2025
SELECT `ID`, `NETTOTAL`, `GROSSTOTAL`, `TOTALCOSTVALUE`, 
       `TOTALPURCHASEVALUE`, `TOTALRETAILSALEVALUE` 
FROM billfinancedetails 
WHERE `ID` < 3314958
  AND `ID` > 3312249
ORDER BY id DESC;
