SELECT 
id,
`BILL_ID`,
ITEM_ID,
`QTY`,
`CREATEDAT`,
`BILLITEMFINANCEDETAILS_ID`,
`NETRATE`,
`RATE`,
`NETVALUE`,
`GROSSVALUE`, 
`RETIRED`
 FROM BILLITEM order by id desc LIMIT 10;

select `ID`,  `QUANTITY`, `QUANTITYBYUNITS`, `CREATEDAT`,  `LINENETRATE`, `LINEGROSSTOTAL`, `GROSSRATE`, `GROSSTOTAL`, `LINEGROSSRATE`, `BILLCOSTRATE`,  `TOTALCOSTRATE`, `LINECOSTRATE`, `LINECOST`, `BILLCOST`, `TOTALCOST`, 
 `LINECOSTRATE`, COSTRATE, PURCHASERATE, RETAILSALERATE , `VALUEATCOSTRATE`, `VALUEATPURCHASERATE`, `VALUEATRETAILRATE` from BILLITEMFINANCEDETAILS order by id desc limit 10;

select
`ID`,
`CREATEDAT`, 
`QTY`,
`FREEQTY`,
`CREATER_ID`,
`BILLITEM_ID`,
`RETAILRATE`,
`PURCHASERATE`,
`COSTRATE` ,
`PURCHASEVALUE`, 
`RETAILVALUE`, 
`COSTVALUE`
from PHARMACEUTICALBILLITEM order by id desc limit 10;


select `ID` , `DTYPE`, `CREATEDAT`,  FROMDEPARTMENT_ID, TODEPARTMENT_ID,   `BILLTYPEATOMIC`, `BILLTYPE`,  `NETTOTAL`, `TOTAL`, `SALEVALUE` , `DEPARTMENT_ID`, `BILLFINANCEDETAILS_ID` from BILL order by id desc limit 10;

select `ID`,  `NETTOTAL`, `GROSSTOTAL`, `TOTALCOSTVALUE`, `TOTALPURCHASEVALUE`, `TOTALRETAILSALEVALUE` from BILLFINANCEDETAILS order by id desc limit 10;