SELECT
  `ID`,
  `CREATEDAT`,

  -- Quantities
  `QUANTITY`,
  `QUANTITYBYUNITS`,

  -- Rates
  `LINENETRATE`,
  `GROSSRATE`,
  `LINEGROSSRATE`,
  `COSTRATE`,
  `PURCHASERATE`,
  `RETAILSALERATE`,
  `LINECOSTRATE`,
  `BILLCOSTRATE`,
  `TOTALCOSTRATE`,

  -- Totals
  `LINEGROSSTOTAL`,
  `GROSSTOTAL`,
  `LINECOST`,
  `BILLCOST`,
  `TOTALCOST`,

  -- Values at Rates
  `VALUEATCOSTRATE`,
  `VALUEATPURCHASERATE`,
  `VALUEATRETAILRATE`
FROM `BILLITEMFINANCEDETAILS`
ORDER BY `ID` DESC
LIMIT 10;
