SET FOREIGN_KEY_CHECKS=0;
drop table person ;
drop table webuser ;
Drop table billfee ;
Drop table bill ;
drop table billitem ;
drop table bill ;
drop table batchbill;
drop table billcomponent ;
drop table billnumber ;
drop table billsession ;
drop table billfeepayment;
drop table cashtransactionhistory;
drop table clinicalfindingvalue;
drop table agenthistory ;
drop table agentreferencebook ;
drop table agentsfees  ;
drop table appointment ;
drop table cashierdrawer ;
drop table cashtransaction ;
drop table dayshift ;
drop table drawer ;
drop table encountercomponent ;
drop table fingerprintrecord ;
drop table hrmvariables ;
drop table hrmvariables_payeetaxrange ;
drop table itembatch ;
drop table logins ;
drop table patientencounter ;
drop table patientflag ;
drop table patientinvestigation ;
drop table patientitem ;
drop table patientreport ;
drop table patientreportitemvalue ;
drop table patientroom ;
drop table payeetaxrange ;
drop table paysheetcomponent ;
drop table userstock ;
drop table WEBUSER;
drop table WEBUSERDASHBOARD;
drop table userstockcontainer ;
drop table webuserdashboard;
drop table webuserdepartment;
drop table webuserpaymentscheme;
drop table webuserprivilege;
drop table webuserrole;
drop TABLE workingtime;
drop table webtheme;
drop table staff;
drop table STOCK;
drop table STOCKHISTORY;
drop table STOCKVARIENTBILLITEM;
drop table sms;
drop table payment;
drop table billentry;
drop table appemail;
SET FOREIGN_KEY_CHECKS=1;