SET FOREIGN_KEY_CHECKS=0;
-- Delete from item where `RETIRED`=true;
-- drop table category where `RETIRED` = true;
-- drop table person where `RETIRED`=true;
-- drop table webuser where `RETIRED`=true;
-- drop table category where  id not in (Select `CATEGORY_ID` from item) and `DTYPE` 
-- in ('PharmaceuticalItemType','PharmaceuticalItemCategory','ServiceCategory','ServiceSubCategory','ConsumableCategory','StoreItemCategory','AssetCategory');
Drop table billfee ;
Drop table bill ;
drop table billitem ;
drop table bill ;
drop table batchbill;
drop table billcomponent ;
drop table billnumber ;
drop table billsession ;
drop table agenthistory ;
drop table agentreferencebook ;
drop table agentsfees  ;
drop table appointment ;
-- drop table cashierdrawer ;
-- drop table cashtransaction ;
-- drop table dayshift ;
-- drop table drawer ;
-- drop table encountercomponent ;
-- drop table fingerprintrecord ;
-- drop table hrmvariables ;
-- drop table hrmvariables_payeetaxrange ;
drop table itembatch ;
-- drop table logins ;
drop table patientencounter ;
drop table patientflag ;
drop table patientinvestigation ;
drop table patientitem ;
drop table patientreport ;
drop table patientreportitemvalue ;
drop table patientroom ;
drop table payeetaxrange ;
drop table paysheetcomponent ;
drop table userstock ;
drop table userstockcontainer ;
SET FOREIGN_KEY_CHECKS=1;