SET FOREIGN_KEY_CHECKS=0;
Delete from item where `RETIRED`=true;
delete from category where `RETIRED` = true;
delete from person where `RETIRED`=true;
delete from webuser where `RETIRED`=true;
delete from category where  id not in (Select `CATEGORY_ID` from item) and `DTYPE` 
in ('PharmaceuticalItemType','PharmaceuticalItemCategory','ServiceCategory','ServiceSubCategory','ConsumableCategory','StoreItemCategory','AssetCategory');
DELETE from billfee where `ID` > 0;
DELETE from bill where `ID` > 0;
DELETE from billitem where `ID` > 0;
DELETE from bill where `ID` > 0;
delete from batchbill where id >0;
DELETE from billcomponent where id > 0;
delete from billnumber where id >0;
delete from billsession where id > 0;
delete from agenthistory where id > 0;
delete from agentreferencebook where id > 0;
delete from agentsfees  where id > 0;
DELETE FROM appointment where id > 0;
delete from cashierdrawer where id > 0;
delete from cashtransaction where id > 0;
delete from dayshift where id >0;
delete from drawer where id >0;
delete from encountercomponent where id > 0;
delete from fingerprintrecord where id > 0;
delete from hrmvariables where id >0;
delete from hrmvariables_payeetaxrange where id > 0;
delete from itembatch where id > 0;
delete from logins where id >0;
delete from patientencounter where id >0;
delete from patientflag where id > 0;
delete from patientinvestigation where id >0;
delete from patientitem where id>0;
delete from patientreport where id > 0;
delete from patientreportitemvalue where id>0;
delete from patientroom where id > 0;
delete from payeetaxrange where id > 0;
delete from paysheetcomponent where id>0;
delete from userstock where id >0;
delete from userstockcontainer where id >0;
SET FOREIGN_KEY_CHECKS=1;