
SET FOREIGN_KEY_CHECKS=0;SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE billSession
DROP FOREIGN KEY FK_BILLSESSION_SERVICESESSION_ID;

ALTER TABLE fee
DROP FOREIGN KEY FK_FEE_SERVICESESSION_ID;
SET FOREIGN_KEY_CHECKS=1;