-- select `ID`, `BHTNO` from patientencounter WHERE `BHTNO` = '2020/364';
SELECT `ID`, `DTYPE`, `BILLTYPE`, `TOTAL`,`CREATEDAT`, `RETIRED` from bill where `PATIENTENCOUNTER_ID` = 8052076;
-- select `ID`, `GROSSVALUE`,`NETVALUE` , `NETRATE`, `RETIRED`, `BILL_ID`,`PATIENTENCOUNTER_ID` from billitem where `BILL_ID` = 8105280 or `REFERENCEBILL_ID` = 8105280;
-- select id, `RETIRED`, `FEEVALUE`,`PAIDVALUE`,`PATIENENCOUNTER_ID`,`STAFF_ID` from billfee where `BILL_ID` = 8105280 or  `REFERENCEBILLFEE_ID`= 8105280;