-- Retire duplicate ConfigOption entries keeping the oldest record
UPDATE CONFIGOPTION co
JOIN (
    SELECT MIN(ID) AS keep_id, OPTIONKEY, SCOPE, INSTITUTION_ID, DEPARTMENT_ID, WEBUSER_ID
    FROM CONFIGOPTION
    WHERE RETIRED = FALSE
    GROUP BY OPTIONKEY, SCOPE, INSTITUTION_ID, DEPARTMENT_ID, WEBUSER_ID
    HAVING COUNT(*) > 1
) dup
  ON co.OPTIONKEY = dup.OPTIONKEY
 AND co.SCOPE = dup.SCOPE
 AND ((co.INSTITUTION_ID <=> dup.INSTITUTION_ID))
 AND ((co.DEPARTMENT_ID <=> dup.DEPARTMENT_ID))
 AND ((co.WEBUSER_ID <=> dup.WEBUSER_ID))
SET co.RETIRED = TRUE,
    co.RETIREDAT = NOW(),
    co.RETIRECOMMENTS = 'duplicate cleanup'
WHERE co.ID <> dup.keep_id
  AND co.RETIRED = FALSE;
