-- Rollback v2.14.0
-- Drops the SVG bed-board columns added in migration v2.14.0.
-- Idempotent and case-insensitive: only drops a column when it exists.

-- CATEGORY.BED_STATUS
SET @tbl = (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES
            WHERE TABLE_SCHEMA = DATABASE() AND UPPER(TABLE_NAME) = 'CATEGORY' LIMIT 1);
SET @col = (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE() AND UPPER(TABLE_NAME) = 'CATEGORY'
              AND UPPER(COLUMN_NAME) = 'BED_STATUS' LIMIT 1);
SET @sql = IF(@col IS NOT NULL,
    CONCAT('ALTER TABLE ', @tbl, ' DROP COLUMN ', @col),
    'SELECT ''CATEGORY.BED_STATUS not found — nothing to drop'' AS info');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- CATEGORY.SVGCHILDVIEW
SET @tbl = (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES
            WHERE TABLE_SCHEMA = DATABASE() AND UPPER(TABLE_NAME) = 'CATEGORY' LIMIT 1);
SET @col = (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE() AND UPPER(TABLE_NAME) = 'CATEGORY'
              AND UPPER(COLUMN_NAME) = 'SVGCHILDVIEW' LIMIT 1);
SET @sql = IF(@col IS NOT NULL,
    CONCAT('ALTER TABLE ', @tbl, ' DROP COLUMN ', @col),
    'SELECT ''CATEGORY.SVGCHILDVIEW not found — nothing to drop'' AS info');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- DEPARTMENT.SVGPARENTVIEW
SET @tbl = (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES
            WHERE TABLE_SCHEMA = DATABASE() AND UPPER(TABLE_NAME) = 'DEPARTMENT' LIMIT 1);
SET @col = (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE() AND UPPER(TABLE_NAME) = 'DEPARTMENT'
              AND UPPER(COLUMN_NAME) = 'SVGPARENTVIEW' LIMIT 1);
SET @sql = IF(@col IS NOT NULL,
    CONCAT('ALTER TABLE ', @tbl, ' DROP COLUMN ', @col),
    'SELECT ''DEPARTMENT.SVGPARENTVIEW not found — nothing to drop'' AS info');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- DEPARTMENT.SVGCHILDVIEW
SET @tbl = (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES
            WHERE TABLE_SCHEMA = DATABASE() AND UPPER(TABLE_NAME) = 'DEPARTMENT' LIMIT 1);
SET @col = (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE() AND UPPER(TABLE_NAME) = 'DEPARTMENT'
              AND UPPER(COLUMN_NAME) = 'SVGCHILDVIEW' LIMIT 1);
SET @sql = IF(@col IS NOT NULL,
    CONCAT('ALTER TABLE ', @tbl, ' DROP COLUMN ', @col),
    'SELECT ''DEPARTMENT.SVGCHILDVIEW not found — nothing to drop'' AS info');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- INSTITUTION.SVGPARENTVIEW
SET @tbl = (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES
            WHERE TABLE_SCHEMA = DATABASE() AND UPPER(TABLE_NAME) = 'INSTITUTION' LIMIT 1);
SET @col = (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE() AND UPPER(TABLE_NAME) = 'INSTITUTION'
              AND UPPER(COLUMN_NAME) = 'SVGPARENTVIEW' LIMIT 1);
SET @sql = IF(@col IS NOT NULL,
    CONCAT('ALTER TABLE ', @tbl, ' DROP COLUMN ', @col),
    'SELECT ''INSTITUTION.SVGPARENTVIEW not found — nothing to drop'' AS info');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- INSTITUTION.SVGCHILDVIEW
SET @tbl = (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES
            WHERE TABLE_SCHEMA = DATABASE() AND UPPER(TABLE_NAME) = 'INSTITUTION' LIMIT 1);
SET @col = (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE() AND UPPER(TABLE_NAME) = 'INSTITUTION'
              AND UPPER(COLUMN_NAME) = 'SVGCHILDVIEW' LIMIT 1);
SET @sql = IF(@col IS NOT NULL,
    CONCAT('ALTER TABLE ', @tbl, ' DROP COLUMN ', @col),
    'SELECT ''INSTITUTION.SVGCHILDVIEW not found — nothing to drop'' AS info');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SELECT 'Rollback v2.14.0 complete' AS status;
