-- Migration v2.1.17: Drop unnecessary indexes on patientsample table
-- Issue: #19399 - Optimize PatientSample bulk operations to prevent DB deadlocks
--
-- Context: patientsample has 39 indexes consuming 142MB for 60MB of data.
-- Many FK indexes have cardinality of 1 (100% NULL) or are never used in queries.
-- Each index adds write-lock overhead during edit() calls, widening the deadlock window.
--
-- UNIVERSAL: Detects actual table name case (PATIENTSAMPLE vs patientsample) so
-- this script works on both case-sensitive (Linux, lower_case_table_names=0) and
-- case-insensitive (Windows) MySQL instances. Uses prepared statements against
-- the real table name obtained from INFORMATION_SCHEMA.
--
-- All DROP FOREIGN KEY and DROP INDEX statements are guarded with INFORMATION_SCHEMA
-- existence checks so the migration is idempotent and safe to re-run. This prevents
-- error 1091 on DBs where MySQL auto-dropped the index when its FK was removed.

SELECT 'Migration v2.1.17 - Drop unnecessary patientsample indexes' AS status;

-- STEP 0: DETECT ACTUAL TABLE NAME CASE

SET @ps_table = (
    SELECT TABLE_NAME
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = DATABASE()
      AND UPPER(TABLE_NAME) = 'PATIENTSAMPLE'
    LIMIT 1
);

SELECT CONCAT('Detected patientsample table as: ', IFNULL(@ps_table, '(not found)')) AS info;
SELECT IF(@ps_table IS NULL,
          'patientsample table not found; v2.1.17 is not applicable and will complete as a successful no-op',
          'patientsample table found; checking removable FK constraints and indexes') AS applicability;

-- STEP 1: PRE-MIGRATION ANALYSIS

SELECT 'BEFORE: Index count and table size' AS status;

SELECT COUNT(*) AS index_count
FROM INFORMATION_SCHEMA.STATISTICS
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table;

SELECT
    ROUND(DATA_LENGTH/1024/1024, 1) AS data_mb,
    ROUND(INDEX_LENGTH/1024/1024, 1) AS index_mb,
    ROUND((DATA_LENGTH+INDEX_LENGTH)/1024/1024, 1) AS total_mb
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table;

-- STEP 2: DROP TIER 1 — 16 indexes on 100% NULL columns (cardinality 1)
-- These columns have zero non-NULL values across all rows.

SELECT 'Dropping Tier 1: 16 FK constraints and indexes on 100% NULL columns' AS status;

SET @fk_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND CONSTRAINT_TYPE = 'FOREIGN KEY' AND CONSTRAINT_NAME = 'FK_PATIENTSAMPLE_RETIRER_ID');
SET @sql = IF(@fk_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_RETIRER_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @idx_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND INDEX_NAME = 'FK_PATIENTSAMPLE_RETIRER_ID');
SET @sql = IF(@idx_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_RETIRER_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @fk_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND CONSTRAINT_TYPE = 'FOREIGN KEY' AND CONSTRAINT_NAME = 'FK_PATIENTSAMPLE_CANCELLEDUSER_ID');
SET @sql = IF(@fk_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_CANCELLEDUSER_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @idx_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND INDEX_NAME = 'FK_PATIENTSAMPLE_CANCELLEDUSER_ID');
SET @sql = IF(@idx_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_CANCELLEDUSER_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @fk_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND CONSTRAINT_TYPE = 'FOREIGN KEY' AND CONSTRAINT_NAME = 'FK_PATIENTSAMPLE_CANCELLDEPARTMENT_ID');
SET @sql = IF(@fk_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_CANCELLDEPARTMENT_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @idx_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND INDEX_NAME = 'FK_PATIENTSAMPLE_CANCELLDEPARTMENT_ID');
SET @sql = IF(@idx_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_CANCELLDEPARTMENT_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @fk_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND CONSTRAINT_TYPE = 'FOREIGN KEY' AND CONSTRAINT_NAME = 'FK_PATIENTSAMPLE_CANCELLINSTITUTION_ID');
SET @sql = IF(@fk_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_CANCELLINSTITUTION_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @idx_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND INDEX_NAME = 'FK_PATIENTSAMPLE_CANCELLINSTITUTION_ID');
SET @sql = IF(@idx_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_CANCELLINSTITUTION_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @fk_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND CONSTRAINT_TYPE = 'FOREIGN KEY' AND CONSTRAINT_NAME = 'FK_PATIENTSAMPLE_DUPLICATEDTO_ID');
SET @sql = IF(@fk_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_DUPLICATEDTO_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @idx_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND INDEX_NAME = 'FK_PATIENTSAMPLE_DUPLICATEDTO_ID');
SET @sql = IF(@idx_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_DUPLICATEDTO_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @fk_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND CONSTRAINT_TYPE = 'FOREIGN KEY' AND CONSTRAINT_NAME = 'FK_PATIENTSAMPLE_DUPLICATEDFROM_ID');
SET @sql = IF(@fk_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_DUPLICATEDFROM_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @idx_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND INDEX_NAME = 'FK_PATIENTSAMPLE_DUPLICATEDFROM_ID');
SET @sql = IF(@idx_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_DUPLICATEDFROM_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @fk_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND CONSTRAINT_TYPE = 'FOREIGN KEY' AND CONSTRAINT_NAME = 'FK_PATIENTSAMPLE_DIVERTEDFROM_ID');
SET @sql = IF(@fk_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_DIVERTEDFROM_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @idx_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND INDEX_NAME = 'FK_PATIENTSAMPLE_DIVERTEDFROM_ID');
SET @sql = IF(@idx_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_DIVERTEDFROM_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @fk_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND CONSTRAINT_TYPE = 'FOREIGN KEY' AND CONSTRAINT_NAME = 'FK_PATIENTSAMPLE_DIVERTEDTO_ID');
SET @sql = IF(@fk_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_DIVERTEDTO_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @idx_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND INDEX_NAME = 'FK_PATIENTSAMPLE_DIVERTEDTO_ID');
SET @sql = IF(@idx_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_DIVERTEDTO_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @fk_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND CONSTRAINT_TYPE = 'FOREIGN KEY' AND CONSTRAINT_NAME = 'FK_PATIENTSAMPLE_SENTTOANALYZERBY_ID');
SET @sql = IF(@fk_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_SENTTOANALYZERBY_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @idx_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND INDEX_NAME = 'FK_PATIENTSAMPLE_SENTTOANALYZERBY_ID');
SET @sql = IF(@idx_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_SENTTOANALYZERBY_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @fk_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND CONSTRAINT_TYPE = 'FOREIGN KEY' AND CONSTRAINT_NAME = 'FK_PATIENTSAMPLE_SENTTOANALYZERDEPARTMENT_ID');
SET @sql = IF(@fk_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_SENTTOANALYZERDEPARTMENT_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @idx_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND INDEX_NAME = 'FK_PATIENTSAMPLE_SENTTOANALYZERDEPARTMENT_ID');
SET @sql = IF(@idx_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_SENTTOANALYZERDEPARTMENT_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @fk_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND CONSTRAINT_TYPE = 'FOREIGN KEY' AND CONSTRAINT_NAME = 'FK_PATIENTSAMPLE_SENTTOANALYZERINSTITUTION_ID');
SET @sql = IF(@fk_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_SENTTOANALYZERINSTITUTION_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @idx_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND INDEX_NAME = 'FK_PATIENTSAMPLE_SENTTOANALYZERINSTITUTION_ID');
SET @sql = IF(@idx_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_SENTTOANALYZERINSTITUTION_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @fk_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND CONSTRAINT_TYPE = 'FOREIGN KEY' AND CONSTRAINT_NAME = 'FK_PATIENTSAMPLE_RECEIVEDFROMANALYZERBY_ID');
SET @sql = IF(@fk_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_RECEIVEDFROMANALYZERBY_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @idx_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND INDEX_NAME = 'FK_PATIENTSAMPLE_RECEIVEDFROMANALYZERBY_ID');
SET @sql = IF(@idx_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_RECEIVEDFROMANALYZERBY_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @fk_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND CONSTRAINT_TYPE = 'FOREIGN KEY' AND CONSTRAINT_NAME = 'FK_PATIENTSAMPLE_RECEIVEDFROMANALYZERDEPARTMENT_ID');
SET @sql = IF(@fk_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_RECEIVEDFROMANALYZERDEPARTMENT_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @idx_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND INDEX_NAME = 'FK_PATIENTSAMPLE_RECEIVEDFROMANALYZERDEPARTMENT_ID');
SET @sql = IF(@idx_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_RECEIVEDFROMANALYZERDEPARTMENT_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Note: this FK was generated without the FK_ prefix (EclipseLink naming for this field); name matches the original migration.
SET @fk_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND CONSTRAINT_TYPE = 'FOREIGN KEY' AND CONSTRAINT_NAME = 'PATIENTSAMPLE_RECEIVEDFROMANALYZERINSTITUTION_ID');
SET @sql = IF(@fk_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY PATIENTSAMPLE_RECEIVEDFROMANALYZERINSTITUTION_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @idx_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND INDEX_NAME = 'PATIENTSAMPLE_RECEIVEDFROMANALYZERINSTITUTION_ID');
SET @sql = IF(@idx_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX PATIENTSAMPLE_RECEIVEDFROMANALYZERINSTITUTION_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @fk_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND CONSTRAINT_TYPE = 'FOREIGN KEY' AND CONSTRAINT_NAME = 'FK_PATIENTSAMPLE_TEST_ID');
SET @sql = IF(@fk_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_TEST_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @idx_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND INDEX_NAME = 'FK_PATIENTSAMPLE_TEST_ID');
SET @sql = IF(@idx_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_TEST_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @fk_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND CONSTRAINT_TYPE = 'FOREIGN KEY' AND CONSTRAINT_NAME = 'FK_PATIENTSAMPLE_PATIENTINVESTIGATION_ID');
SET @sql = IF(@fk_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_PATIENTINVESTIGATION_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @idx_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND INDEX_NAME = 'FK_PATIENTSAMPLE_PATIENTINVESTIGATION_ID');
SET @sql = IF(@idx_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_PATIENTINVESTIGATION_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- STEP 3: DROP TIER 2 — 7 indexes with low cardinality (2-5) and never queried in code

SELECT 'Dropping Tier 2: 7 FK constraints and indexes on low-cardinality, never-queried columns' AS status;

SET @fk_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND CONSTRAINT_TYPE = 'FOREIGN KEY' AND CONSTRAINT_NAME = 'FK_PATIENTSAMPLE_BARCODEGENERATEDINSTITUTION_ID');
SET @sql = IF(@fk_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_BARCODEGENERATEDINSTITUTION_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @idx_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND INDEX_NAME = 'FK_PATIENTSAMPLE_BARCODEGENERATEDINSTITUTION_ID');
SET @sql = IF(@idx_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_BARCODEGENERATEDINSTITUTION_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @fk_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND CONSTRAINT_TYPE = 'FOREIGN KEY' AND CONSTRAINT_NAME = 'FK_PATIENTSAMPLE_SAMPLEREJECTEDBY_ID');
SET @sql = IF(@fk_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_SAMPLEREJECTEDBY_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @idx_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND INDEX_NAME = 'FK_PATIENTSAMPLE_SAMPLEREJECTEDBY_ID');
SET @sql = IF(@idx_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_SAMPLEREJECTEDBY_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @fk_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND CONSTRAINT_TYPE = 'FOREIGN KEY' AND CONSTRAINT_NAME = 'FK_PATIENTSAMPLE_SAMPLERECEIVEDATLABINSTITUTION_ID');
SET @sql = IF(@fk_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_SAMPLERECEIVEDATLABINSTITUTION_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @idx_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND INDEX_NAME = 'FK_PATIENTSAMPLE_SAMPLERECEIVEDATLABINSTITUTION_ID');
SET @sql = IF(@idx_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_SAMPLERECEIVEDATLABINSTITUTION_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @fk_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND CONSTRAINT_TYPE = 'FOREIGN KEY' AND CONSTRAINT_NAME = 'FK_PATIENTSAMPLE_SAMPLECOLLECTEDINSTITUTION_ID');
SET @sql = IF(@fk_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_SAMPLECOLLECTEDINSTITUTION_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @idx_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND INDEX_NAME = 'FK_PATIENTSAMPLE_SAMPLECOLLECTEDINSTITUTION_ID');
SET @sql = IF(@idx_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_SAMPLECOLLECTEDINSTITUTION_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @fk_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND CONSTRAINT_TYPE = 'FOREIGN KEY' AND CONSTRAINT_NAME = 'FK_PATIENTSAMPLE_SAMPLERECEIVEDATLABDEPARTMENT_ID');
SET @sql = IF(@fk_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_SAMPLERECEIVEDATLABDEPARTMENT_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @idx_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND INDEX_NAME = 'FK_PATIENTSAMPLE_SAMPLERECEIVEDATLABDEPARTMENT_ID');
SET @sql = IF(@idx_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_SAMPLERECEIVEDATLABDEPARTMENT_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @fk_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND CONSTRAINT_TYPE = 'FOREIGN KEY' AND CONSTRAINT_NAME = 'FK_PATIENTSAMPLE_SAMPLECOLLECTEDDEPARTMENT_ID');
SET @sql = IF(@fk_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_SAMPLECOLLECTEDDEPARTMENT_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @idx_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND INDEX_NAME = 'FK_PATIENTSAMPLE_SAMPLECOLLECTEDDEPARTMENT_ID');
SET @sql = IF(@idx_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_SAMPLECOLLECTEDDEPARTMENT_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @fk_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND CONSTRAINT_TYPE = 'FOREIGN KEY' AND CONSTRAINT_NAME = 'FK_PATIENTSAMPLE_BARCODEGENERATEDDEPARTMENT_ID');
SET @sql = IF(@fk_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_BARCODEGENERATEDDEPARTMENT_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @idx_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table AND INDEX_NAME = 'FK_PATIENTSAMPLE_BARCODEGENERATEDDEPARTMENT_ID');
SET @sql = IF(@idx_exists > 0, CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_BARCODEGENERATEDDEPARTMENT_ID'), 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- STEP 4: POST-MIGRATION VERIFICATION

SELECT 'AFTER: Index count and table size' AS status;

SELECT COUNT(*) AS index_count
FROM INFORMATION_SCHEMA.STATISTICS
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table;

SELECT
    ROUND(DATA_LENGTH/1024/1024, 1) AS data_mb,
    ROUND(INDEX_LENGTH/1024/1024, 1) AS index_mb,
    ROUND((DATA_LENGTH+INDEX_LENGTH)/1024/1024, 1) AS total_mb
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table;

SELECT 'Migration v2.1.17 completed — 23 FK constraints and up to 23 indexes dropped (46 objects total)' AS final_status;
