-- Migration v2.1.17: Drop unnecessary indexes on patientsample table
-- Issue: #19399 - Optimize PatientSample bulk operations to prevent DB deadlocks
--
-- Context: patientsample has 39 indexes consuming 142MB for 60MB of data.
-- Many FK indexes have cardinality of 1 (100% NULL) or are never used in queries.
-- Each index adds write-lock overhead during edit() calls, widening the deadlock window.
--
-- UNIVERSAL: Detects actual table name case (PATIENTSAMPLE vs patientsample) so
-- this script works on both case-sensitive (Linux, lower_case_table_names=0) and
-- case-insensitive (Windows) MySQL instances. Uses prepared statements against
-- the real table name obtained from INFORMATION_SCHEMA.

SELECT 'Migration v2.1.17 - Drop unnecessary patientsample indexes' AS status;

-- STEP 0: DETECT ACTUAL TABLE NAME CASE

SET @ps_table = (
    SELECT TABLE_NAME
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = DATABASE()
      AND UPPER(TABLE_NAME) = 'PATIENTSAMPLE'
    LIMIT 1
);

SELECT CONCAT('Detected patientsample table as: ', IFNULL(@ps_table, '(not found)')) AS info;

-- STEP 1: PRE-MIGRATION ANALYSIS

SELECT 'BEFORE: Index count and table size' AS status;

SELECT COUNT(*) AS index_count
FROM INFORMATION_SCHEMA.STATISTICS
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table;

SELECT
    ROUND(DATA_LENGTH/1024/1024, 1) AS data_mb,
    ROUND(INDEX_LENGTH/1024/1024, 1) AS index_mb,
    ROUND((DATA_LENGTH+INDEX_LENGTH)/1024/1024, 1) AS total_mb
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table;

-- STEP 2: DROP TIER 1 — 16 indexes on 100% NULL columns (cardinality 1)
-- These columns have zero non-NULL values across all rows.

SELECT 'Dropping Tier 1: 16 FK constraints and indexes on 100% NULL columns' AS status;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_RETIRER_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_RETIRER_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_CANCELLEDUSER_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_CANCELLEDUSER_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_CANCELLDEPARTMENT_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_CANCELLDEPARTMENT_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_CANCELLINSTITUTION_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_CANCELLINSTITUTION_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_DUPLICATEDTO_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_DUPLICATEDTO_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_DUPLICATEDFROM_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_DUPLICATEDFROM_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_DIVERTEDFROM_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_DIVERTEDFROM_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_DIVERTEDTO_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_DIVERTEDTO_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_SENTTOANALYZERBY_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_SENTTOANALYZERBY_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_SENTTOANALYZERDEPARTMENT_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_SENTTOANALYZERDEPARTMENT_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_SENTTOANALYZERINSTITUTION_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_SENTTOANALYZERINSTITUTION_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_RECEIVEDFROMANALYZERBY_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_RECEIVEDFROMANALYZERBY_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_RECEIVEDFROMANALYZERDEPARTMENT_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_RECEIVEDFROMANALYZERDEPARTMENT_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY PATIENTSAMPLE_RECEIVEDFROMANALYZERINSTITUTION_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX PATIENTSAMPLE_RECEIVEDFROMANALYZERINSTITUTION_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_TEST_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_TEST_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_PATIENTINVESTIGATION_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_PATIENTINVESTIGATION_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- STEP 3: DROP TIER 2 — 7 indexes with low cardinality (2-5) and never queried in code

SELECT 'Dropping Tier 2: 7 FK constraints and indexes on low-cardinality, never-queried columns' AS status;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_BARCODEGENERATEDINSTITUTION_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_BARCODEGENERATEDINSTITUTION_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_SAMPLEREJECTEDBY_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_SAMPLEREJECTEDBY_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_SAMPLERECEIVEDATLABINSTITUTION_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_SAMPLERECEIVEDATLABINSTITUTION_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_SAMPLECOLLECTEDINSTITUTION_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_SAMPLECOLLECTEDINSTITUTION_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_SAMPLERECEIVEDATLABDEPARTMENT_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_SAMPLERECEIVEDATLABDEPARTMENT_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_SAMPLECOLLECTEDDEPARTMENT_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_SAMPLECOLLECTEDDEPARTMENT_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP FOREIGN KEY FK_PATIENTSAMPLE_BARCODEGENERATEDDEPARTMENT_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' DROP INDEX FK_PATIENTSAMPLE_BARCODEGENERATEDDEPARTMENT_ID');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- STEP 4: POST-MIGRATION VERIFICATION

SELECT 'AFTER: Index count and table size' AS status;

SELECT COUNT(*) AS index_count
FROM INFORMATION_SCHEMA.STATISTICS
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table;

SELECT
    ROUND(DATA_LENGTH/1024/1024, 1) AS data_mb,
    ROUND(INDEX_LENGTH/1024/1024, 1) AS index_mb,
    ROUND((DATA_LENGTH+INDEX_LENGTH)/1024/1024, 1) AS total_mb
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @ps_table;

SELECT 'Migration v2.1.17 completed — 23 indexes dropped' AS final_status;
