-- Migration v2.1.17: Drop unnecessary indexes on patientsample table
-- Issue: #19399 - Optimize PatientSample bulk operations to prevent DB deadlocks
--
-- Context: patientsample has 39 indexes consuming 142MB for 60MB of data.
-- Many FK indexes have cardinality of 1 (100% NULL) or are never used in queries.
-- Each index adds write-lock overhead during edit() calls, widening the deadlock window.

SELECT 'Migration v2.1.17 - Drop unnecessary patientsample indexes' AS status;

-- STEP 1: PRE-MIGRATION ANALYSIS

SELECT 'BEFORE: Index count and table size' AS status;

SELECT COUNT(*) AS index_count
FROM information_schema.STATISTICS
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PATIENTSAMPLE';

SELECT
    ROUND(DATA_LENGTH/1024/1024, 1) AS data_mb,
    ROUND(INDEX_LENGTH/1024/1024, 1) AS index_mb,
    ROUND((DATA_LENGTH+INDEX_LENGTH)/1024/1024, 1) AS total_mb
FROM information_schema.TABLES
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PATIENTSAMPLE';

-- STEP 2: DROP TIER 1 — 16 indexes on 100% NULL columns (cardinality 1)
-- These columns have zero non-NULL values across all rows.

SELECT 'Dropping Tier 1: 16 FK constraints and indexes on 100% NULL columns' AS status;

ALTER TABLE PATIENTSAMPLE DROP FOREIGN KEY FK_PATIENTSAMPLE_RETIRER_ID;
ALTER TABLE PATIENTSAMPLE DROP INDEX FK_PATIENTSAMPLE_RETIRER_ID;

ALTER TABLE PATIENTSAMPLE DROP FOREIGN KEY FK_PATIENTSAMPLE_CANCELLEDUSER_ID;
ALTER TABLE PATIENTSAMPLE DROP INDEX FK_PATIENTSAMPLE_CANCELLEDUSER_ID;

ALTER TABLE PATIENTSAMPLE DROP FOREIGN KEY FK_PATIENTSAMPLE_CANCELLDEPARTMENT_ID;
ALTER TABLE PATIENTSAMPLE DROP INDEX FK_PATIENTSAMPLE_CANCELLDEPARTMENT_ID;

ALTER TABLE PATIENTSAMPLE DROP FOREIGN KEY FK_PATIENTSAMPLE_CANCELLINSTITUTION_ID;
ALTER TABLE PATIENTSAMPLE DROP INDEX FK_PATIENTSAMPLE_CANCELLINSTITUTION_ID;

ALTER TABLE PATIENTSAMPLE DROP FOREIGN KEY FK_PATIENTSAMPLE_DUPLICATEDTO_ID;
ALTER TABLE PATIENTSAMPLE DROP INDEX FK_PATIENTSAMPLE_DUPLICATEDTO_ID;

ALTER TABLE PATIENTSAMPLE DROP FOREIGN KEY FK_PATIENTSAMPLE_DUPLICATEDFROM_ID;
ALTER TABLE PATIENTSAMPLE DROP INDEX FK_PATIENTSAMPLE_DUPLICATEDFROM_ID;

ALTER TABLE PATIENTSAMPLE DROP FOREIGN KEY FK_PATIENTSAMPLE_DIVERTEDFROM_ID;
ALTER TABLE PATIENTSAMPLE DROP INDEX FK_PATIENTSAMPLE_DIVERTEDFROM_ID;

ALTER TABLE PATIENTSAMPLE DROP FOREIGN KEY FK_PATIENTSAMPLE_DIVERTEDTO_ID;
ALTER TABLE PATIENTSAMPLE DROP INDEX FK_PATIENTSAMPLE_DIVERTEDTO_ID;

ALTER TABLE PATIENTSAMPLE DROP FOREIGN KEY FK_PATIENTSAMPLE_SENTTOANALYZERBY_ID;
ALTER TABLE PATIENTSAMPLE DROP INDEX FK_PATIENTSAMPLE_SENTTOANALYZERBY_ID;

ALTER TABLE PATIENTSAMPLE DROP FOREIGN KEY FK_PATIENTSAMPLE_SENTTOANALYZERDEPARTMENT_ID;
ALTER TABLE PATIENTSAMPLE DROP INDEX FK_PATIENTSAMPLE_SENTTOANALYZERDEPARTMENT_ID;

ALTER TABLE PATIENTSAMPLE DROP FOREIGN KEY FK_PATIENTSAMPLE_SENTTOANALYZERINSTITUTION_ID;
ALTER TABLE PATIENTSAMPLE DROP INDEX FK_PATIENTSAMPLE_SENTTOANALYZERINSTITUTION_ID;

ALTER TABLE PATIENTSAMPLE DROP FOREIGN KEY FK_PATIENTSAMPLE_RECEIVEDFROMANALYZERBY_ID;
ALTER TABLE PATIENTSAMPLE DROP INDEX FK_PATIENTSAMPLE_RECEIVEDFROMANALYZERBY_ID;

ALTER TABLE PATIENTSAMPLE DROP FOREIGN KEY FK_PATIENTSAMPLE_RECEIVEDFROMANALYZERDEPARTMENT_ID;
ALTER TABLE PATIENTSAMPLE DROP INDEX FK_PATIENTSAMPLE_RECEIVEDFROMANALYZERDEPARTMENT_ID;

ALTER TABLE PATIENTSAMPLE DROP FOREIGN KEY PATIENTSAMPLE_RECEIVEDFROMANALYZERINSTITUTION_ID;
ALTER TABLE PATIENTSAMPLE DROP INDEX PATIENTSAMPLE_RECEIVEDFROMANALYZERINSTITUTION_ID;

ALTER TABLE PATIENTSAMPLE DROP FOREIGN KEY FK_PATIENTSAMPLE_TEST_ID;
ALTER TABLE PATIENTSAMPLE DROP INDEX FK_PATIENTSAMPLE_TEST_ID;

ALTER TABLE PATIENTSAMPLE DROP FOREIGN KEY FK_PATIENTSAMPLE_PATIENTINVESTIGATION_ID;
ALTER TABLE PATIENTSAMPLE DROP INDEX FK_PATIENTSAMPLE_PATIENTINVESTIGATION_ID;

-- STEP 3: DROP TIER 2 — 7 indexes with low cardinality (2-5) and never queried in code

SELECT 'Dropping Tier 2: 7 FK constraints and indexes on low-cardinality, never-queried columns' AS status;

ALTER TABLE PATIENTSAMPLE DROP FOREIGN KEY FK_PATIENTSAMPLE_BARCODEGENERATEDINSTITUTION_ID;
ALTER TABLE PATIENTSAMPLE DROP INDEX FK_PATIENTSAMPLE_BARCODEGENERATEDINSTITUTION_ID;

ALTER TABLE PATIENTSAMPLE DROP FOREIGN KEY FK_PATIENTSAMPLE_SAMPLEREJECTEDBY_ID;
ALTER TABLE PATIENTSAMPLE DROP INDEX FK_PATIENTSAMPLE_SAMPLEREJECTEDBY_ID;

ALTER TABLE PATIENTSAMPLE DROP FOREIGN KEY FK_PATIENTSAMPLE_SAMPLERECEIVEDATLABINSTITUTION_ID;
ALTER TABLE PATIENTSAMPLE DROP INDEX FK_PATIENTSAMPLE_SAMPLERECEIVEDATLABINSTITUTION_ID;

ALTER TABLE PATIENTSAMPLE DROP FOREIGN KEY FK_PATIENTSAMPLE_SAMPLECOLLECTEDINSTITUTION_ID;
ALTER TABLE PATIENTSAMPLE DROP INDEX FK_PATIENTSAMPLE_SAMPLECOLLECTEDINSTITUTION_ID;

ALTER TABLE PATIENTSAMPLE DROP FOREIGN KEY FK_PATIENTSAMPLE_SAMPLERECEIVEDATLABDEPARTMENT_ID;
ALTER TABLE PATIENTSAMPLE DROP INDEX FK_PATIENTSAMPLE_SAMPLERECEIVEDATLABDEPARTMENT_ID;

ALTER TABLE PATIENTSAMPLE DROP FOREIGN KEY FK_PATIENTSAMPLE_SAMPLECOLLECTEDDEPARTMENT_ID;
ALTER TABLE PATIENTSAMPLE DROP INDEX FK_PATIENTSAMPLE_SAMPLECOLLECTEDDEPARTMENT_ID;

ALTER TABLE PATIENTSAMPLE DROP FOREIGN KEY FK_PATIENTSAMPLE_BARCODEGENERATEDDEPARTMENT_ID;
ALTER TABLE PATIENTSAMPLE DROP INDEX FK_PATIENTSAMPLE_BARCODEGENERATEDDEPARTMENT_ID;

-- STEP 4: POST-MIGRATION VERIFICATION

SELECT 'AFTER: Index count and table size' AS status;

SELECT COUNT(*) AS index_count
FROM information_schema.STATISTICS
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PATIENTSAMPLE';

SELECT
    ROUND(DATA_LENGTH/1024/1024, 1) AS data_mb,
    ROUND(INDEX_LENGTH/1024/1024, 1) AS index_mb,
    ROUND((DATA_LENGTH+INDEX_LENGTH)/1024/1024, 1) AS total_mb
FROM information_schema.TABLES
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PATIENTSAMPLE';

SELECT 'Migration v2.1.17 completed — 23 indexes dropped' AS final_status;
