-- Rollback v2.1.17: Re-create dropped FK constraints and indexes on patientsample
-- This restores all 23 FK constraints and their associated indexes.
--
-- UNIVERSAL: Detects actual table name case for every referenced table
-- (PATIENTSAMPLE, WEBUSER, DEPARTMENT, INSTITUTION, ITEM, PATIENTINVESTIGATION)
-- so this script works on both case-sensitive (Linux, lower_case_table_names=0)
-- and case-insensitive (Windows) MySQL instances.

SELECT 'Rollback v2.1.17 - Re-creating patientsample FK constraints and indexes' AS status;

-- STEP 0: DETECT ACTUAL TABLE NAMES

SET @ps_table = (
    SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = DATABASE() AND UPPER(TABLE_NAME) = 'PATIENTSAMPLE' LIMIT 1
);

SET @webuser_table = (
    SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = DATABASE() AND UPPER(TABLE_NAME) = 'WEBUSER' LIMIT 1
);

SET @department_table = (
    SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = DATABASE() AND UPPER(TABLE_NAME) = 'DEPARTMENT' LIMIT 1
);

SET @institution_table = (
    SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = DATABASE() AND UPPER(TABLE_NAME) = 'INSTITUTION' LIMIT 1
);

SET @item_table = (
    SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = DATABASE() AND UPPER(TABLE_NAME) = 'ITEM' LIMIT 1
);

SET @pi_table = (
    SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = DATABASE() AND UPPER(TABLE_NAME) = 'PATIENTINVESTIGATION' LIMIT 1
);

SELECT 'Detected tables:' AS info,
       @ps_table AS patientsample,
       @webuser_table AS webuser,
       @department_table AS department,
       @institution_table AS institution,
       @item_table AS item,
       @pi_table AS patientinvestigation;

-- TIER 1: 16 FK constraints on 100% NULL columns

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' ADD CONSTRAINT FK_PATIENTSAMPLE_RETIRER_ID ',
    'FOREIGN KEY (RETIRER_ID) REFERENCES ', @webuser_table, '(ID)');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' ADD CONSTRAINT FK_PATIENTSAMPLE_CANCELLEDUSER_ID ',
    'FOREIGN KEY (CANCELLEDUSER_ID) REFERENCES ', @webuser_table, '(ID)');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' ADD CONSTRAINT FK_PATIENTSAMPLE_CANCELLDEPARTMENT_ID ',
    'FOREIGN KEY (CANCELLDEPARTMENT_ID) REFERENCES ', @department_table, '(ID)');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' ADD CONSTRAINT FK_PATIENTSAMPLE_CANCELLINSTITUTION_ID ',
    'FOREIGN KEY (CANCELLINSTITUTION_ID) REFERENCES ', @institution_table, '(ID)');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' ADD CONSTRAINT FK_PATIENTSAMPLE_DUPLICATEDTO_ID ',
    'FOREIGN KEY (DUPLICATEDTO_ID) REFERENCES ', @ps_table, '(ID)');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' ADD CONSTRAINT FK_PATIENTSAMPLE_DUPLICATEDFROM_ID ',
    'FOREIGN KEY (DUPLICATEDFROM_ID) REFERENCES ', @ps_table, '(ID)');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' ADD CONSTRAINT FK_PATIENTSAMPLE_DIVERTEDFROM_ID ',
    'FOREIGN KEY (DIVERTEDFROM_ID) REFERENCES ', @ps_table, '(ID)');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' ADD CONSTRAINT FK_PATIENTSAMPLE_DIVERTEDTO_ID ',
    'FOREIGN KEY (DIVERTEDTO_ID) REFERENCES ', @ps_table, '(ID)');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' ADD CONSTRAINT FK_PATIENTSAMPLE_SENTTOANALYZERBY_ID ',
    'FOREIGN KEY (SENTTOANALYZERBY_ID) REFERENCES ', @webuser_table, '(ID)');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' ADD CONSTRAINT FK_PATIENTSAMPLE_SENTTOANALYZERDEPARTMENT_ID ',
    'FOREIGN KEY (SENTTOANALYZERDEPARTMENT_ID) REFERENCES ', @department_table, '(ID)');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' ADD CONSTRAINT FK_PATIENTSAMPLE_SENTTOANALYZERINSTITUTION_ID ',
    'FOREIGN KEY (SENTTOANALYZERINSTITUTION_ID) REFERENCES ', @institution_table, '(ID)');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' ADD CONSTRAINT FK_PATIENTSAMPLE_RECEIVEDFROMANALYZERBY_ID ',
    'FOREIGN KEY (RECEIVEDFROMANALYZERBY_ID) REFERENCES ', @webuser_table, '(ID)');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' ADD CONSTRAINT FK_PATIENTSAMPLE_RECEIVEDFROMANALYZERDEPARTMENT_ID ',
    'FOREIGN KEY (RECEIVEDFROMANALYZERDEPARTMENT_ID) REFERENCES ', @department_table, '(ID)');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' ADD CONSTRAINT PATIENTSAMPLE_RECEIVEDFROMANALYZERINSTITUTION_ID ',
    'FOREIGN KEY (RECEIVEDFROMANALYZERINSTITUTION_ID) REFERENCES ', @institution_table, '(ID)');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' ADD CONSTRAINT FK_PATIENTSAMPLE_TEST_ID ',
    'FOREIGN KEY (TEST_ID) REFERENCES ', @item_table, '(ID)');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' ADD CONSTRAINT FK_PATIENTSAMPLE_PATIENTINVESTIGATION_ID ',
    'FOREIGN KEY (PATIENTINVESTIGATION_ID) REFERENCES ', @pi_table, '(ID)');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- TIER 2: 7 FK constraints on low-cardinality, never-queried columns

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' ADD CONSTRAINT FK_PATIENTSAMPLE_BARCODEGENERATEDINSTITUTION_ID ',
    'FOREIGN KEY (BARCODEGENERATEDINSTITUTION_ID) REFERENCES ', @institution_table, '(ID)');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' ADD CONSTRAINT FK_PATIENTSAMPLE_SAMPLEREJECTEDBY_ID ',
    'FOREIGN KEY (SAMPLEREJECTEDBY_ID) REFERENCES ', @webuser_table, '(ID)');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' ADD CONSTRAINT FK_PATIENTSAMPLE_SAMPLERECEIVEDATLABINSTITUTION_ID ',
    'FOREIGN KEY (SAMPLERECEIVEDATLABINSTITUTION_ID) REFERENCES ', @institution_table, '(ID)');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' ADD CONSTRAINT FK_PATIENTSAMPLE_SAMPLECOLLECTEDINSTITUTION_ID ',
    'FOREIGN KEY (SAMPLECOLLECTEDINSTITUTION_ID) REFERENCES ', @institution_table, '(ID)');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' ADD CONSTRAINT FK_PATIENTSAMPLE_SAMPLERECEIVEDATLABDEPARTMENT_ID ',
    'FOREIGN KEY (SAMPLERECEIVEDATLABDEPARTMENT_ID) REFERENCES ', @department_table, '(ID)');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' ADD CONSTRAINT FK_PATIENTSAMPLE_SAMPLECOLLECTEDDEPARTMENT_ID ',
    'FOREIGN KEY (SAMPLECOLLECTEDDEPARTMENT_ID) REFERENCES ', @department_table, '(ID)');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('ALTER TABLE ', @ps_table, ' ADD CONSTRAINT FK_PATIENTSAMPLE_BARCODEGENERATEDDEPARTMENT_ID ',
    'FOREIGN KEY (BARCODEGENERATEDDEPARTMENT_ID) REFERENCES ', @department_table, '(ID)');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT 'Rollback v2.1.17 completed — 23 FK constraints and indexes restored' AS final_status;
