-- Rollback v2.1.17: Re-create dropped FK constraints and indexes on patientsample
-- This restores all 23 FK constraints and their associated indexes.

SELECT 'Rollback v2.1.17 - Re-creating patientsample FK constraints and indexes' AS status;

-- TIER 1: 16 FK constraints on 100% NULL columns

ALTER TABLE PATIENTSAMPLE ADD CONSTRAINT FK_PATIENTSAMPLE_RETIRER_ID
    FOREIGN KEY (RETIRER_ID) REFERENCES WEBUSER(ID);

ALTER TABLE PATIENTSAMPLE ADD CONSTRAINT FK_PATIENTSAMPLE_CANCELLEDUSER_ID
    FOREIGN KEY (CANCELLEDUSER_ID) REFERENCES WEBUSER(ID);

ALTER TABLE PATIENTSAMPLE ADD CONSTRAINT FK_PATIENTSAMPLE_CANCELLDEPARTMENT_ID
    FOREIGN KEY (CANCELLDEPARTMENT_ID) REFERENCES DEPARTMENT(ID);

ALTER TABLE PATIENTSAMPLE ADD CONSTRAINT FK_PATIENTSAMPLE_CANCELLINSTITUTION_ID
    FOREIGN KEY (CANCELLINSTITUTION_ID) REFERENCES INSTITUTION(ID);

ALTER TABLE PATIENTSAMPLE ADD CONSTRAINT FK_PATIENTSAMPLE_DUPLICATEDTO_ID
    FOREIGN KEY (DUPLICATEDTO_ID) REFERENCES PATIENTSAMPLE(ID);

ALTER TABLE PATIENTSAMPLE ADD CONSTRAINT FK_PATIENTSAMPLE_DUPLICATEDFROM_ID
    FOREIGN KEY (DUPLICATEDFROM_ID) REFERENCES PATIENTSAMPLE(ID);

ALTER TABLE PATIENTSAMPLE ADD CONSTRAINT FK_PATIENTSAMPLE_DIVERTEDFROM_ID
    FOREIGN KEY (DIVERTEDFROM_ID) REFERENCES PATIENTSAMPLE(ID);

ALTER TABLE PATIENTSAMPLE ADD CONSTRAINT FK_PATIENTSAMPLE_DIVERTEDTO_ID
    FOREIGN KEY (DIVERTEDTO_ID) REFERENCES PATIENTSAMPLE(ID);

ALTER TABLE PATIENTSAMPLE ADD CONSTRAINT FK_PATIENTSAMPLE_SENTTOANALYZERBY_ID
    FOREIGN KEY (SENTTOANALYZERBY_ID) REFERENCES WEBUSER(ID);

ALTER TABLE PATIENTSAMPLE ADD CONSTRAINT FK_PATIENTSAMPLE_SENTTOANALYZERDEPARTMENT_ID
    FOREIGN KEY (SENTTOANALYZERDEPARTMENT_ID) REFERENCES DEPARTMENT(ID);

ALTER TABLE PATIENTSAMPLE ADD CONSTRAINT FK_PATIENTSAMPLE_SENTTOANALYZERINSTITUTION_ID
    FOREIGN KEY (SENTTOANALYZERINSTITUTION_ID) REFERENCES INSTITUTION(ID);

ALTER TABLE PATIENTSAMPLE ADD CONSTRAINT FK_PATIENTSAMPLE_RECEIVEDFROMANALYZERBY_ID
    FOREIGN KEY (RECEIVEDFROMANALYZERBY_ID) REFERENCES WEBUSER(ID);

ALTER TABLE PATIENTSAMPLE ADD CONSTRAINT FK_PATIENTSAMPLE_RECEIVEDFROMANALYZERDEPARTMENT_ID
    FOREIGN KEY (RECEIVEDFROMANALYZERDEPARTMENT_ID) REFERENCES DEPARTMENT(ID);

ALTER TABLE PATIENTSAMPLE ADD CONSTRAINT PATIENTSAMPLE_RECEIVEDFROMANALYZERINSTITUTION_ID
    FOREIGN KEY (RECEIVEDFROMANALYZERINSTITUTION_ID) REFERENCES INSTITUTION(ID);

ALTER TABLE PATIENTSAMPLE ADD CONSTRAINT FK_PATIENTSAMPLE_TEST_ID
    FOREIGN KEY (TEST_ID) REFERENCES ITEM(ID);

ALTER TABLE PATIENTSAMPLE ADD CONSTRAINT FK_PATIENTSAMPLE_PATIENTINVESTIGATION_ID
    FOREIGN KEY (PATIENTINVESTIGATION_ID) REFERENCES PATIENTINVESTIGATION(ID);

-- TIER 2: 7 FK constraints on low-cardinality, never-queried columns

ALTER TABLE PATIENTSAMPLE ADD CONSTRAINT FK_PATIENTSAMPLE_BARCODEGENERATEDINSTITUTION_ID
    FOREIGN KEY (BARCODEGENERATEDINSTITUTION_ID) REFERENCES INSTITUTION(ID);

ALTER TABLE PATIENTSAMPLE ADD CONSTRAINT FK_PATIENTSAMPLE_SAMPLEREJECTEDBY_ID
    FOREIGN KEY (SAMPLEREJECTEDBY_ID) REFERENCES WEBUSER(ID);

ALTER TABLE PATIENTSAMPLE ADD CONSTRAINT FK_PATIENTSAMPLE_SAMPLERECEIVEDATLABINSTITUTION_ID
    FOREIGN KEY (SAMPLERECEIVEDATLABINSTITUTION_ID) REFERENCES INSTITUTION(ID);

ALTER TABLE PATIENTSAMPLE ADD CONSTRAINT FK_PATIENTSAMPLE_SAMPLECOLLECTEDINSTITUTION_ID
    FOREIGN KEY (SAMPLECOLLECTEDINSTITUTION_ID) REFERENCES INSTITUTION(ID);

ALTER TABLE PATIENTSAMPLE ADD CONSTRAINT FK_PATIENTSAMPLE_SAMPLERECEIVEDATLABDEPARTMENT_ID
    FOREIGN KEY (SAMPLERECEIVEDATLABDEPARTMENT_ID) REFERENCES DEPARTMENT(ID);

ALTER TABLE PATIENTSAMPLE ADD CONSTRAINT FK_PATIENTSAMPLE_SAMPLECOLLECTEDDEPARTMENT_ID
    FOREIGN KEY (SAMPLECOLLECTEDDEPARTMENT_ID) REFERENCES DEPARTMENT(ID);

ALTER TABLE PATIENTSAMPLE ADD CONSTRAINT FK_PATIENTSAMPLE_BARCODEGENERATEDDEPARTMENT_ID
    FOREIGN KEY (BARCODEGENERATEDDEPARTMENT_ID) REFERENCES DEPARTMENT(ID);

SELECT 'Rollback v2.1.17 completed — 23 FK constraints and indexes restored' AS final_status;
