package com.divudi.service;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.ejb.Asynchronous;
import javax.ejb.Stateless;
import javax.ejb.TransactionAttribute;
import javax.ejb.TransactionAttributeType;

/**
 * Fetches the wiki-hosted DDL "Last Update" version string used to detect
 * whether a deployed schema is current, and runs the version comparison in
 * the background so callers never block on the outbound HTTP request.
 *
 * Shared by {@link DatabaseMigrationService}'s automatic post-startup check
 * and by the manual "Check Missing Fields" flow in
 * {@code DataAdministrationController} — both used to duplicate this
 * fetch/regex logic independently.
 *
 * @author Dr M H B Ariyaratne
 */
@Stateless
public class DatabaseMigrationVersionCheckService {

    private static final Logger LOGGER = Logger.getLogger(DatabaseMigrationVersionCheckService.class.getName());
    private static final String WIKI_DDL_URL = "https://github.com/hmislk/hmis/wiki/Database-Schema-DDL-Generation-Guide";
    private static final Pattern WIKI_DDL_VERSION_PATTERN
            = Pattern.compile("Last Update\\s*-\\s*(\\d{4}\\.\\d{2}\\.\\d{2}\\s+\\d{2}[.:]\\d{2})");

    /**
     * A genuine "Last Update" version string as generated by the
     * {@code generate-ddl} skill ({@code date '+%Y.%m.%d %H.%M'}, e.g.
     * {@code "2026.09.10 04.00"}) or its legacy {@code HH:MM}-separated form.
     * Anything else — an unset value, or a legacy marker like
     * {@code "UNCHECKED"} (the seeded default for a hospital that has never
     * had its schema verified against the wiki at all, see
     * {@code ConfigOptionApplicationController.loadDatabaseVersionConfigurationDefaults()})
     * — doesn't match, and {@link #isStoredVersionOlderThanWiki(String, String)}
     * treats a non-matching {@code stored} value as "definitely stale" (not
     * "can't tell, don't block") so a genuinely never-verified hospital keeps
     * showing the pending banner exactly as before issue #23679's fix (only
     * {@code CONFIRMED} still short-circuits, via
     * {@code DatabaseMigrationService.init()}, before this comparison ever
     * runs).
     */
    private static final Pattern VERSION_SHAPE_PATTERN
            = Pattern.compile("^\\d{4}\\.\\d{2}\\.\\d{2}\\s+\\d{2}[.:]\\d{2}$");

    /**
     * Fetches the wiki page and extracts the "Last Update" DDL version
     * string, e.g. "2026.08.07 04.00". Returns null on any network or parse
     * failure — callers must treat null as "unknown, fall back to the
     * legacy check" rather than raising an error.
     */
    @TransactionAttribute(TransactionAttributeType.NOT_SUPPORTED)
    public String fetchWikiDdlVersion() {
        HttpURLConnection conn = null;
        try {
            URL url = new URL(WIKI_DDL_URL);
            conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod("GET");
            conn.setConnectTimeout(5000);
            conn.setReadTimeout(10000);
            conn.setRequestProperty("User-Agent", "HMIS-Schema-Checker/1.0");
            int status = conn.getResponseCode();
            if (status == 200) {
                try (BufferedReader reader = new BufferedReader(
                        new InputStreamReader(conn.getInputStream(), StandardCharsets.UTF_8))) {
                    String line;
                    while ((line = reader.readLine()) != null) {
                        Matcher m = WIKI_DDL_VERSION_PATTERN.matcher(line);
                        if (m.find()) {
                            return m.group(1).trim();
                        }
                    }
                }
            }
        } catch (Exception e) {
            // Network or parse failure — return null so caller falls back to legacy check
        } finally {
            if (conn != null) {
                conn.disconnect();
            }
        }
        return null;
    }

    /**
     * Compares the wiki's current DDL version against the caller's stored
     * version and, only when the stored version is a real, parseable
     * version string that is already at or after the wiki's, marks
     * migration complete. Runs on a container-managed background thread —
     * {@code @Asynchronous} only takes effect when this method is invoked
     * through an injected (proxied) reference to this bean, never via
     * self-invocation.
     *
     * Before issue #23679, this only cleared the banner on exact string
     * equality between the stored and wiki versions — so a hospital whose
     * stored version was already current but not byte-identical (or
     * genuinely ahead of a momentarily-stale wiki read) stayed stuck
     * "pending" indefinitely with no way to tell that apart from real DDL
     * drift. Now the comparison is a real "is the stored version older than
     * (or simply not confirmed as being at least as new as) the wiki's"
     * check — see {@link #isStoredVersionOlderThanWiki} for the exact
     * contract, including why an unset/{@code "UNCHECKED"} stored version
     * still correctly keeps the banner pending rather than being treated as
     * "safe".
     *
     * Any failure (wiki unreachable, timeout, parse error) is swallowed at
     * FINE level: this is a best-effort convenience check, and it must
     * never surface an error to end users or affect the migrationPending
     * default the caller already has.
     */
    @Asynchronous
    @TransactionAttribute(TransactionAttributeType.NOT_SUPPORTED)
    public void checkAndUpdateMigrationStatus(DatabaseMigrationService migrationService) {
        if (migrationService == null) {
            return;
        }
        try {
            String wikiVersion = fetchWikiDdlVersion();
            if (wikiVersion == null) {
                LOGGER.fine("DatabaseMigrationVersionCheckService: wiki DDL version unreachable during background check.");
                return;
            }
            String storedVersion = migrationService.readStoredDdlVersion();
            if (isStoredVersionOlderThanWiki(storedVersion, wikiVersion)) {
                LOGGER.warning("DatabaseMigrationVersionCheckService: stored DDL version [" + storedVersion
                        + "] is not confirmed current against the wiki's version [" + wikiVersion + "] — either "
                        + "genuine schema drift or a never-verified schema; migration banner stays pending until "
                        + "an admin runs the DDL sync on mf.xhtml.");
                return;
            }
            migrationService.markMigrationComplete();
            LOGGER.info("DatabaseMigrationVersionCheckService: background check confirmed schema is up to date "
                    + "(stored version [" + storedVersion + "], wiki version [" + wikiVersion + "]) — migration banner cleared.");
        } catch (Exception e) {
            LOGGER.log(Level.FINE, "DatabaseMigrationVersionCheckService: background DDL version check failed.", e);
        }
    }

    /**
     * True unless {@code stored} is a genuine "Last Update" version string
     * (see {@link #VERSION_SHAPE_PATTERN}) that sorts at or after
     * {@code wiki} — i.e. true whenever the stored schema version is either
     * provably older than the wiki's current one, or not a real version at
     * all (so staleness can't be ruled out).
     *
     * Returns {@code false} ("not stale, safe to clear the banner") only for
     * the one case that's a confirmed non-issue: {@code stored} is a real,
     * parseable version string that is lexicographically equal to or after
     * {@code wiki} — already current, or (unusually) ahead.
     *
     * Returns {@code true} ("treat as stale/pending") for everything else:
     * <ul>
     * <li>{@code wiki} is {@code null} (wiki unreachable) — with nothing to
     * compare against, this method is never called in that case (see
     * {@link #checkAndUpdateMigrationStatus}, which returns early on a
     * {@code null} wiki version before ever reaching this check); documented
     * here for completeness of the contract if called directly.</li>
     * <li>{@code stored} is {@code null} or doesn't match the version-string
     * shape — covers an unset value and the {@code "UNCHECKED"} seeded
     * default for a hospital whose schema has never been verified against
     * the wiki at all. Before issue #23679, a non-{@code "CONFIRMED"} stored
     * value fell through to {@code !wiki.equals(stored)} and correctly
     * stayed "pending" in this exact case — this preserves that behavior
     * rather than treating an unverified hospital as "safe".</li>
     * <li>{@code stored} is a real version string but sorts strictly before
     * {@code wiki} — genuine drift.</li>
     * </ul>
     *
     * The {@code YYYY.MM.DD HH.MM} version format (fixed-width, zero-padded
     * — see {@code generate-ddl} skill's {@code date '+%Y.%m.%d %H.%M'})
     * sorts correctly under plain lexicographic {@link String#compareTo},
     * so no date parsing is needed; the legacy {@code HH:MM} colon separator
     * is normalized to {@code .} first so both forms compare consistently.
     */
    public boolean isStoredVersionOlderThanWiki(String stored, String wiki) {
        if (wiki == null || stored == null) {
            return true;
        }
        if (!VERSION_SHAPE_PATTERN.matcher(stored).matches() || !VERSION_SHAPE_PATTERN.matcher(wiki).matches()) {
            return true;
        }
        String normalizedStored = stored.replace(':', '.');
        String normalizedWiki = wiki.replace(':', '.');
        return normalizedStored.compareTo(normalizedWiki) < 0;
    }
}
