-- Migration v2.1.16: Fix GRN Return and Direct Purchase Return bills missing COMPLETED
-- Issue: #18261

SELECT 'Migration v2.1.16 - Fix GRN/Direct Purchase return completed fields' AS status;

-- STEP 1: PRE-MIGRATION ANALYSIS

SELECT 'BEFORE: Returns missing completed=true' AS status;
SELECT BILLTYPE, BILLTYPEATOMIC, COUNT(*) AS total,
    SUM(CASE WHEN COMPLETED = 0 THEN 1 ELSE 0 END) AS not_completed,
    SUM(CASE WHEN APPROVEAT IS NULL THEN 1 ELSE 0 END) AS missing_approveat
FROM BILL
WHERE BILLTYPEATOMIC IN ('PHARMACY_GRN_RETURN', 'PHARMACY_DIRECT_PURCHASE_REFUND')
  AND CANCELLED = 0
  AND RETIRED = 0
GROUP BY BILLTYPE, BILLTYPEATOMIC;

-- STEP 2: SET COMPLETED=1 ONLY FOR ROWS THAT HAVE BEEN APPROVED (APPROVEAT IS NOT NULL)

UPDATE BILL
SET COMPLETED = 1
WHERE BILLTYPEATOMIC IN ('PHARMACY_GRN_RETURN', 'PHARMACY_DIRECT_PURCHASE_REFUND')
  AND CANCELLED = 0
  AND RETIRED = 0
  AND COMPLETED = 0
  AND APPROVEAT IS NOT NULL;

SELECT 'Step 1: Set completed=true for approved returns' AS description,
       ROW_COUNT() AS affected_rows;

-- STEP 3: COUNT ROWS INTENTIONALLY SKIPPED (APPROVEAT IS NULL - NOT YET APPROVED)

SELECT 'Step 2: Returns with APPROVEAT IS NULL left unchanged (not approved)' AS description,
       COUNT(*) AS skipped_rows
FROM BILL
WHERE BILLTYPEATOMIC IN ('PHARMACY_GRN_RETURN', 'PHARMACY_DIRECT_PURCHASE_REFUND')
  AND CANCELLED = 0
  AND RETIRED = 0
  AND COMPLETED = 0
  AND APPROVEAT IS NULL;

-- STEP 4: POST-MIGRATION VERIFICATION

SELECT 'AFTER: Approved returns still missing completed=true (should be 0)' AS status;
SELECT BILLTYPE, BILLTYPEATOMIC, COUNT(*) AS total,
    SUM(CASE WHEN COMPLETED = 0 THEN 1 ELSE 0 END) AS not_completed,
    SUM(CASE WHEN APPROVEAT IS NULL THEN 1 ELSE 0 END) AS missing_approveat
FROM BILL
WHERE BILLTYPEATOMIC IN ('PHARMACY_GRN_RETURN', 'PHARMACY_DIRECT_PURCHASE_REFUND')
  AND CANCELLED = 0
  AND RETIRED = 0
GROUP BY BILLTYPE, BILLTYPEATOMIC;

SELECT 'Sample of fixed records' AS status;
SELECT ID, BILLTYPE, BILLTYPEATOMIC, CREATEDAT, APPROVEAT, COMPLETED, CANCELLED
FROM BILL
WHERE BILLTYPEATOMIC IN ('PHARMACY_GRN_RETURN', 'PHARMACY_DIRECT_PURCHASE_REFUND')
  AND CANCELLED = 0
  AND RETIRED = 0
ORDER BY ID DESC
LIMIT 10;

SELECT
    CASE
        WHEN (SELECT COUNT(*) FROM BILL
              WHERE BILLTYPEATOMIC IN ('PHARMACY_GRN_RETURN', 'PHARMACY_DIRECT_PURCHASE_REFUND')
                AND CANCELLED = 0
                AND RETIRED = 0
                AND APPROVEAT IS NOT NULL
                AND COMPLETED = 0) = 0
        THEN 'Migration v2.1.16 SUCCESS: All approved GRN/Direct Purchase returns now have completed=true'
        ELSE 'Migration v2.1.16 PARTIAL: Some approved returns still missing completed=true'
    END AS final_result;

SELECT 'Migration v2.1.16 completed' AS final_status;
