package com.divudi.core.data.dto.pharmacy;

import com.divudi.core.data.PaymentMethod;
import java.util.List;

/**
 * Parameter object bundling everything
 * {@code GrnApprovingNativeSqlService.approveGrn(...)} needs from the
 * controller for one GRN Approve action. Plain POJO, built in-memory by the
 * controller (GrnCostingNativeSqlController, not yet built as of this class)
 * -- never round-tripped through a JPQL constructor.
 *
 * Values that legacy computes via config lookups, session state, or a
 * payment-method switch (bill number strings, the balance-by-payment-method
 * rule in {@code GrnCostingController.updateBalanceForGrn()}, the pre/post
 * total negation) are deliberately kept OUT of this native service and
 * computed by the controller instead -- this request just carries the
 * already-decided results in. See the class-level Javadoc on
 * GrnApprovingNativeSqlService for why the sign-flip in particular must be
 * pre-computed by the caller rather than derived here.
 *
 * Related issue: #22874
 */
public class GrnApproveRequest {

    private long billId;

    // The originating Purchase Order's own approved bill id (Bill.referenceBill
    // on the GRN pre-bill). Null when this GRN has no PO reference (direct GRN).
    private Long poBillId;

    // Bill-number strings, config-driven and generated by the controller
    // (BillNumberBean...), written verbatim onto bill.deptId / bill.insId.
    private String deptId;
    private String insId;

    private long editorId;
    private long approveUserId;

    private long departmentId;
    private long institutionId;

    private List<GrnApproveLineData> lines;

    private PaymentMethod paymentMethod;
    private boolean generatePayment;

    // The bill's positive netTotal BEFORE the post-approve sign negation --
    // used verbatim as Payment.paidValue. Must NOT be re-derived from the bill
    // row inside the service, since by the time insertPayment() runs the bill
    // row has already been sign-flipped by the updateBillTotals() call.
    private double prePositiveNetTotalForPayment;

    // Already sign-flipped (negated) by the controller -- written as-is via
    // GrnCostingNativeSqlService.updateBillTotals().
    private double postNegationNetTotal;
    private double postNegationTotal;

    // Computed by the controller's payment-method switch
    // (mirrors GrnCostingController.updateBalanceForGrn()).
    private double balanceValue;

    // Whether the referenced PO is now fully received (controller's JPQL read
    // via isPurchaseOrderFullyReceived()); drives markPurchaseOrderFullyIssued().
    private boolean poFullyReceived;

    public long getBillId() {
        return billId;
    }

    public void setBillId(long billId) {
        this.billId = billId;
    }

    public Long getPoBillId() {
        return poBillId;
    }

    public void setPoBillId(Long poBillId) {
        this.poBillId = poBillId;
    }

    public String getDeptId() {
        return deptId;
    }

    public void setDeptId(String deptId) {
        this.deptId = deptId;
    }

    public String getInsId() {
        return insId;
    }

    public void setInsId(String insId) {
        this.insId = insId;
    }

    public long getEditorId() {
        return editorId;
    }

    public void setEditorId(long editorId) {
        this.editorId = editorId;
    }

    public long getApproveUserId() {
        return approveUserId;
    }

    public void setApproveUserId(long approveUserId) {
        this.approveUserId = approveUserId;
    }

    public long getDepartmentId() {
        return departmentId;
    }

    public void setDepartmentId(long departmentId) {
        this.departmentId = departmentId;
    }

    public long getInstitutionId() {
        return institutionId;
    }

    public void setInstitutionId(long institutionId) {
        this.institutionId = institutionId;
    }

    public List<GrnApproveLineData> getLines() {
        return lines;
    }

    public void setLines(List<GrnApproveLineData> lines) {
        this.lines = lines;
    }

    public PaymentMethod getPaymentMethod() {
        return paymentMethod;
    }

    public void setPaymentMethod(PaymentMethod paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    public boolean isGeneratePayment() {
        return generatePayment;
    }

    public void setGeneratePayment(boolean generatePayment) {
        this.generatePayment = generatePayment;
    }

    public double getPrePositiveNetTotalForPayment() {
        return prePositiveNetTotalForPayment;
    }

    public void setPrePositiveNetTotalForPayment(double prePositiveNetTotalForPayment) {
        this.prePositiveNetTotalForPayment = prePositiveNetTotalForPayment;
    }

    public double getPostNegationNetTotal() {
        return postNegationNetTotal;
    }

    public void setPostNegationNetTotal(double postNegationNetTotal) {
        this.postNegationNetTotal = postNegationNetTotal;
    }

    public double getPostNegationTotal() {
        return postNegationTotal;
    }

    public void setPostNegationTotal(double postNegationTotal) {
        this.postNegationTotal = postNegationTotal;
    }

    public double getBalanceValue() {
        return balanceValue;
    }

    public void setBalanceValue(double balanceValue) {
        this.balanceValue = balanceValue;
    }

    public boolean isPoFullyReceived() {
        return poFullyReceived;
    }

    public void setPoFullyReceived(boolean poFullyReceived) {
        this.poFullyReceived = poFullyReceived;
    }
}
