-- Rollback v2.6.0: Drop ITEMBATCHARCHIVE, STOCKARCHIVE, and PBI archive pointer column

SET @pbi_table = (
    SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = DATABASE() AND UPPER(TABLE_NAME) = 'PHARMACEUTICALBILLITEM'
    LIMIT 1
);

-- Remove ARCHIVEDITEMBATCH_ID from PHARMACEUTICALBILLITEM

SET @col_exists = (
    SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND UPPER(TABLE_NAME) = 'PHARMACEUTICALBILLITEM'
      AND UPPER(COLUMN_NAME) = 'ARCHIVEDITEMBATCH_ID'
);
SET @sql = IF(@pbi_table IS NULL OR @col_exists = 0, 'SELECT 1',
    CONCAT('ALTER TABLE ', @pbi_table, ' DROP COLUMN ARCHIVEDITEMBATCH_ID'));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Drop STOCKARCHIVE

SET @starch_exists = (
    SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = DATABASE() AND UPPER(TABLE_NAME) = 'STOCKARCHIVE'
);
SET @sql = IF(@starch_exists = 0, 'SELECT 1', 'DROP TABLE STOCKARCHIVE');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Drop ITEMBATCHARCHIVE

SET @ibarch_exists = (
    SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = DATABASE() AND UPPER(TABLE_NAME) = 'ITEMBATCHARCHIVE'
);
SET @sql = IF(@ibarch_exists = 0, 'SELECT 1', 'DROP TABLE ITEMBATCHARCHIVE');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT 'Rollback v2.6.0 completed — archive tables and PBI column dropped (if they existed)' AS status;
