name: Block Branch Creation from Staging

on:
  create:
    branches:
      - '**'

jobs:
  prevent-from-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch is created from staging
        env:
          HEAD_BRANCH: ${{ github.ref }}
          BASE_BRANCH: ${{ github.event.base_ref }}
        run: |
          echo "Created branch: $HEAD_BRANCH"
          echo "Base branch: $BASE_BRANCH"

          CREATED_BRANCH="$HEAD_BRANCH"
          BASE_REF="$BASE_BRANCH"

          if [ -z "$BASE_REF" ]; then
            echo "No base branch info available — skipping."
            exit 0
          fi

          if [[ "$BASE_REF" == "-staging" ]]; then
            echo "❌ Creating branches from $BASE_REF is not allowed."
            exit 1
          fi

          echo "✅ Branch creation is allowed."
