name: Build

on:
  push:
    branches:
      - dev-ci-cd-setup

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Printing Hello Build
        run: |
          sleep 5
          echo 'Hello, Build!'
