name: Coop Test environment(QA) ci-cd workflow

on: 
    push: 
        branches:
            - coop-test
            
jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: checkout code
              uses: actions/checkout@v4
              
            - name: setup JDK 11
              uses: actions/setup-java@v4
              with: 
                distribution: 'temurin'
                java-version: '11'
                
            - name: Cache Maven Packages
              uses: actions/cache@v3
              with:
                path: ~/.m2
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                ${{ runner.os }}-maven-

            - name: Update JDBC Data Sources in persistence.xml
               run: |
                 sed -i 's|<jta-data-source>${JDBC_DATASOURCE}</jta-data-source>|<jta-data-source>jdbc/ruhunu</jta-data-source>|' src/main/resources/META-INF/persistence.xml
                 sed -i 's|<jta-data-source>${JDBC_AUDIT_DATASOURCE}</jta-data-source>|<jta-data-source>jdbc/ruhunuAudit</jta-data-source>|' src/main/resources/META-INF/persistence.xml
          
            - name: Verify JDBC Data Sources in persistence.xml
                run: |
                  grep '<jta-data-source>' src/main/resources/META-INF/persistence.xml 
            

