name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level selection'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Tags of the workflow'
        required: true
        type: string

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
