name: QA Database Dump and Replace

on:
  workflow_dispatch:
    inputs:
      fromEnv:
        description: 'Select Environment to Dump'
        required: true
        type: choice
        options:
          - COOP_Dev
          - COOP_Prod
          - Ruhunu_Prod
          - MP_Prod
      toEnv:
        description: 'Select Environment to Replace'
        required: true
        type: choice
        options:
          - QA
      date:
        description: 'Select Date (YYYY-MM-DD)'
        required: true

jobs:
  deployment:
    name: Schedule DB Swap
    runs-on: ubuntu-latest
    steps:
      - name: Schedule DB Swap on Observability VM
        env:
          OBSERVABILITY_IP: ${{ secrets.OBSERVABILITY_SERVER_IP }}
          OBSERVABILITY_SSH_KEY: ${{ secrets.OBSERVABILITY_SSH_PRIVATE_KEY }}
          FROM_ENV: ${{ inputs.fromEnv }}
          TO_ENV: ${{ inputs.toEnv }}
          DATE: ${{ inputs.date }}
        run: |
          echo "$OBSERVABILITY_SSH_KEY" > observability_key.pem
          chmod 600 observability_key.pem
          
          UTC_TIME=$(date -d "${DATE}T02:00:00+05:30" -u "+%H:%M %Y-%m-%d")

          HOUR=$(echo "$UTC_TIME" | awk '{print $1}' | cut -d':' -f1)
          MINUTE=$(echo "$UTC_TIME" | awk '{print $1}' | cut -d':' -f2)
          UTC_DATE=$(echo "$UTC_TIME" | awk '{print $2}')
          
          ssh -o StrictHostKeyChecking=no -i observability_key.pem azureuser@$OBSERVABILITY_IP "
            echo '/home/azureuser/utils/swap_databases/db_swap.sh $FROM_ENV $TO_ENV' | at $HOUR:$MINUTE $UTC_DATE
          "
          rm observability_key.pem
