name: Production Merge Validation

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - development

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch name
        env:
          HEAD_BRANCH: ${{ github.head_ref }}
          BASE_BRANCH: ${{ github.base_ref }}
        run: |
          echo "Source branch: $HEAD_BRANCH"
          echo "Target branch: $BASE_BRANCH"
          SOURCE="$HEAD_BRANCH"
          TARGET="$BASE_BRANCH"

          if [[ "$TARGET" == *-prod ]]; then
            if [[ "$SOURCE" == *-dev || "$SOURCE" == *-stg || "$SOURCE" == "hims-qa1" || "$SOURCE" == "hims-qa2" || "$SOURCE" == "development" ]]; then
              echo "❌ Merging from $SOURCE to $TARGET is not allowed."
              exit 1
            fi
          fi

          echo "✅ Merge is allowed."
