name: Restart NGINX & VMs

on:
  workflow_dispatch:
    inputs:
      selectedAction:
        description: 'Action'
        required: true
        type: choice
        options:
          - Reload NGINX
          - Restart VM
      selectedServer:
        description: 'Select Server'
        required: true
        type: choice
        options:
          - Development(4.240.39.63)
          - QA(4.240.43.211)

jobs:
  run_script_remote_server:
    name: Run Script on Remote Server
    runs-on: ubuntu-latest
    steps:
      - name: Run Script Remote Server
        env:
          SERVER_IP: ${{ secrets.OBSERVABILITY_SERVER_IP }}
          SERVER_SSH_KEY: ${{ secrets.OBSERVABILITY_SSH_PRIVATE_KEY }}
          SELECTED_SERVER: ${{ inputs.selectedServer }}
        run: |
          echo "$SERVER_SSH_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          ssh -o StrictHostKeyChecking=no -i private_key.pem azureuser@$SERVER_IP "
            echo '/home/azureuser/utils/server_utils/restart_nginx_vms.sh $SELECTED_SERVER'
          "
          rm private_key.pem
